export const statData = [
  {
    heading: "Team Leaders",
    tlData: [
      {
        avatar: "avatar",
        name: "Josh Allen",
        pos: "QB",
        rating: "2,018",
      },
      {
        avatar: "avatar",
        name: "Josh Allen",
        pos: "CB",
        rating: "2,018",
      },
      {
        avatar: "avatar",
        name: "Josh Allen",
        pos: "AB",
        rating: "2,018",
      },
      {
        avatar: "avatar",
        name: "Josh Allen",
        pos: "QB",
        rating: "2,018",
      },
      {
        avatar: "avatar",
        name: "Josh Allen",
        pos: "QB",
        rating: "2,018",
      },
    ],
  },
  {
    heading: "Passing",
    header: [
      "NAME",
      "GP",
      "CMP",
      "ATT",
      "CMP%",
      "YDS",
      "AVG",
      "YDS/G",
      "LNG",
      "TD",
      "INT",
      "SACK",
      "SYL",
      "RTG",
    ],
    data: [
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        cmp: 5,
        att: 2,
        cmp2: 0,
        yds: 0.914,
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: 174,
        sack: 12,
        syl: 82,
        rtg: 105.0,
      },
      {
        name: "Matt Barkley",
        pos: "QB",
        gp: 10,
        cmp: 5,
        att: 2,
        cmp2: 0,
        yds: 0.714,
        avg: "2-1",
        ydsg: "3-1",
        lng: "3-0",
        td: "4-2",
        int: 174,
        sack: 12,
        syl: 82,
        rtg: 105.0,
      },
    ],
  },
  {
    heading: "Rushing",
    header: [
      "NAME",
      "GP",
      "ATT",
      "DEF",
      "DEF%",
      "YDS",
      "AVG",
      "LNG",
      "BIG",
      "TD",
      "YDS/G",
      "FUM",
      "LST",
      "FD",
    ],
    data: [
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        att: 2,
        yds: 0.714,
        avg: "2-1",
        lng: "3-0",
        big: "3-0",
        td: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        fd: 105,
      },
      {
        name: "Matt Barkley",
        pos: "QB",
        gp: 5,
        att: 2,
        yds: 0.714,
        avg: "2-1",
        lng: "3-0",
        big: "3-0",
        td: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        att: 2,
        yds: 0.714,
        avg: "2-1",
        lng: "3-0",
        big: "3-0",
        td: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        att: 2,
        yds: 0.714,
        avg: "2-1",
        lng: "3-0",
        big: "3-0",
        td: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        att: 2,
        yds: 0.714,
        avg: "2-1",
        lng: "3-0",
        big: "3-0",
        td: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        fd: 105,
      },
    ],
  },
  {
    heading: "Recieving",
    header: [
      "NAME",
      "GP",
      "REC",
      "TGTS",
      "DEF%",
      "YDS",
      "AVG",
      "TD",
      "LNG",
      "BIG",
      "YDS/G",
      "FUM",
      "LST",
      "YAC",
      "FD",
    ],
    data: [
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        rec: 2,
        tgts: 2,
        yds: 0.714,
        avg: "2-1",
        td: "3-1",
        lng: "3-0",
        big: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        yac: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        rec: 2,
        tgts: 2,
        yds: 0.714,
        avg: "2-1",
        td: "3-1",
        lng: "3-0",
        big: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        yac: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        rec: 2,
        tgts: 2,
        yds: 0.714,
        avg: "2-1",
        td: "3-1",
        lng: "3-0",
        big: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        yac: 82,
        fd: 105,
      },
      {
        name: "Josh Allen",
        pos: "QB",
        gp: 5,
        rec: 2,
        tgts: 2,
        yds: 0.714,
        avg: "2-1",
        td: "3-1",
        lng: "3-0",
        big: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        yac: 82,
        fd: 105,
      },
      {
        name: "Matt Barkley",
        pos: "QB",
        gp: 5,
        rec: 2,
        tgts: 2,
        yds: 0.714,
        avg: "2-1",
        td: "3-1",
        lng: "3-0",
        big: "4-2",
        ydsg: 174,
        fum: 12,
        lst: 82,
        yac: 82,
        fd: 105,
      },
    ],
  },
];
