export const scheduleDataRegular = [
  {
    type: "main",
    season: "Regular Season",
    header: [
      "WK",
      "DATE",
      "OPPONENT",
      "RESULT",
      "WL",
      "HI PASS",
      "HI RUSH",
      "HI REC",
    ],
    data: [
      {
        id: 1,
        wk: 1,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        result1: "W",
        result2: "27-17",
        wl: "1-0",
        hipass1: "Allen",
        hipass2: 312,
        hirush1: "Allen",
        hirush2: 312,
        hirec1: "Allen",
        hirec2: 312,
      },
      {
        id: 2,
        wk: 2,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        result1: "W",
        result2: "27-17",
        wl: "1-0",
        hipass1: "Allen",
        hipass2: 312,
        hirush1: "Allen",
        hirush2: 312,
        hirec1: "Allen",
        hirec2: 312,
      },
    ],
  },
  {
    type: "secondary",
    season: null,
    header: ["WK", "DATE", "OPPONENT", "TIME", "TV", "TICKETS"],
    data: [
      {
        id: 1,
        wk: 3,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        time: "11:30 PM",
        tv: "",
        tickets: "Tickets as low as $40",
      },
      {
        id: 1,
        wk: 4,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        time: "11:30 PM",
        tv: "",
        tickets: "Tickets as low as $40",
      },
    ],
  },
  {
    type: "main",
    season: "Pre Season",
    header: [
      "WK",
      "DATE",
      "OPPONENT",
      "RESULT",
      "WL",
      "HI PASS",
      "HI RUSH",
      "HI REC",
    ],
    data: [
      {
        id: 1,
        wk: 1,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        result1: "",
        result2: "",
        wl: "",
        hipass1: "",
        hipass2: "",
        hirush1: "CANCELED",
        hirush2: "",
        hirec1: "",
        hirec2: "",
      },
      {
        id: 1,
        wk: 1,
        date: "Sun, 13 Sep",
        opponentSign: "vs",
        opponentLogo: "logo",
        opponentName: "New York",
        result1: "",
        result2: "",
        wl: "",
        hipass1: "",
        hipass2: "",
        hirush1: "CANCELED",
        hirush2: "",
        hirec1: "",
        hirec2: "",
      },
    ],
  },
];
export const scheduleDataPreseason = [];
