export const rosterData = [
  {
    type: "Offense",
    data: [
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
    ],
  },
  {
    type: "Deffense",
    data: [
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
      {
        name: {
          avatar: "img",
          name: "Josh Allen",
          number: 17,
        },
        pos: "QB",
        age: 24,
        ht: "1.96 m",
        wt: "107 kg",
        exp: 3,
        college: "Wyoming",
      },
    ],
  },
];
